### ISSUE TITLE
numba.errors.TypingError in findmotif tutorial

### ISSUE THREAD

**Issue by larisaok** [pinellolab/GRAFIMO#6]
Hello, @kant and @ManuelTgn,

Thank you for creating GRAFIMO! I would like to use it, but I have encountered errors, that I failed to resolve. I have tried to go through the tutorial for finding motifs and got the following error

```Process Process-129:=====================================    ] 92.2% Complete
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lokorokova/.local/lib/python3.6/site-packages/grafimo/score_sequences.py", line 271, in score_seqs
    seq, score_matrix, pval_mat, min_score, scale, width, offset
  File "/usr/lib64/python3.6/site-packages/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
  File "/usr/lib64/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/lib64/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/lib64/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 779, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 738, in _compile_bytecode
    return self._compile_core()
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 725, in _compile_core
    res = pm.run(self.status)
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 248, in run
    raise patched_exception
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 240, in run
    stage()
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
    self.locals)
  File "/usr/lib64/python3.6/site-packages/numba/compiler.py", line 881, in type_inference_stage
    infer.propagate()
  File "/usr/lib64/python3.6/site-packages/numba/typeinfer.py", line 846, in propagate
    raise errors[0]
  File "/usr/lib64/python3.6/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/usr/lib64/python3.6/site-packages/numba/typeinfer.py", line 503, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/usr/lib64/python3.6/site-packages/numba/typeinfer.py", line 452, in resolve
    raise TypingError(msg, loc=self.loc)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid usage of getitem with parameters (str, int64)
 * parameterized
File "../../home/lokorokova/.local/lib/python3.6/site-packages/grafimo/score_sequences.py", line 340
[1] During: typing of intrinsic-call at /home/lokorokova/.local/lib/python3.6/site-packages/grafimo/score_sequences.py (340)
```

The whole log is attached as a file. 
[grafimo.log](https://github.com/pinellolab/GRAFIMO/files/9496353/grafimo.log)

Versions of packages, used in this case
vg version v1.43.0
pandas 1.1.5
numpy 1.19.5
statsmodels 0.12.2
sphinx 5.1.1
numba 0.53.1
colorama 0.4.5

I would be very grateful for help!
Larsa

**Comment by ManuelTgn** [comment]
Hi Larsa,

thank you for using GRAFIMO! I tried to reproduce the error with a fresh installation of the tool (the python packages versions match those you listed), however I didn't get any error running the tutorial. Which version of GRAFIMO are you using? On which OS are you trying to run the tool?

Manuel

**Comment by larisaok** [comment]
Manuel, 

I am using GRAFIMO version 1.1.4, and OS is opensuse 15.3. Just in case - is it possible to run on a personal laptop (at least, the tutorial part)? I am more flexible in trying other ways to install dependencies on my computer in comparison with the university cluster.

Larisa

**Comment by ManuelTgn** [comment]
Hi, 

I think that the error you get is due to the GRAFIMO version you're running. Did you install it via PIP, conda, or from the Github repo? 
Installing GRAFIMO v1.1.5 from the Github repo should solve the issues you encountered. In v1.1.5, it have been fixed some bugs that arise with recent versions of the package on which the tool depends. 

Let me know if you still get the same error running GRAFIMO 1.1.5.

Manuel

**Comment by larisaok** [comment]
I installed GRAFIMO via PIP3, but now I followed your advice and installed it from Github. Despite having the newer version, the error still occurs.

**Comment by ManuelTgn** [comment]
Hi Larisa,

I've been able to reproduce your error by downgrading numba to v0.53.1. BTW I solved the error just by upgrading numba to the current version. 

Let me know if that worked for you, too.

Manuel

**Comment by larisaok** [comment]
Hi Manuel!

I have managed to upgrade numba after upgrading python from 3.6 to 3.7 and now everything works. So, I think the main problem was python version. By the way, I have also tried to install GRAFIMO on my personal laptop via docker and that also worked perfectly. 

Thank you for your help,
Larisa.
